declare module '@env' {r
    export const RAZORPAY_API_KEY_ID: string;
    export const RAZORPAY_API_KEY_SECRET: string;
    export const RAZORPAY_API_URL: string;
    export const FIREBASE_API_KEY: string;
    export const FIREBASE_AUTH_DOMAIN: string;
    export const FIREBASE_PROJECT_ID: string;
    export const FIREBASE_STORAGE_BUCKET: string;
    export const FIREBASE_MESSAGING_SENDER_ID: string;
    export const FIREBASE_APP_ID: string;
    export const FIREBASE_MEASUREMENT_ID: string;
    export const GITHUB_EXERCISES_URL: string;
    export const GITHUB_EXERCISE_IMAGE_URL_PREFIX: string;
    export const EXPO_PUBLIC_GOOGLE_WEB_CLIENT_ID: string;
    export const EXPO_PUBLIC_FIREBASE_IOS_CLIENT_ID: string;
    export const EXPO_PUBLIC_FIREBASE_ANDROID_CLIENT_ID: string;
    export const GOOGLE_SERVICE_JSON: string;
    export const GOOGLE_SERVICE_PLIST: string;
}