export const fallbackExercises = [
  {
    id: 'fallback-back-1',
    name: 'Pull-up',
    force: 'pull',
    level: 'intermediate',
    mechanic: 'compound',
    equipment: 'body only',
    primaryMuscles: ['lats'],
    secondaryMuscles: ['biceps', 'middle back'],
    instructions: [
      'Grab the bar with your palms facing away from you.',
      'Pull your chest toward the bar while keeping your body controlled.',
      'Lower yourself until your arms are extended, then repeat.',
    ],
    category: 'strength',
  },
  {
    id: 'fallback-back-2',
    name: 'Bent Over Barbell Row',
    force: 'pull',
    level: 'intermediate',
    mechanic: 'compound',
    equipment: 'barbell',
    primaryMuscles: ['middle back'],
    secondaryMuscles: ['lats', 'biceps'],
    instructions: [
      'Hinge at your hips with a neutral spine.',
      'Pull the bar toward your lower ribs.',
      'Lower the bar under control and keep your torso steady.',
    ],
    category: 'strength',
  },
  {
    id: 'fallback-arms-1',
    name: 'Dumbbell Curl',
    force: 'pull',
    level: 'beginner',
    mechanic: 'isolation',
    equipment: 'dumbbell',
    primaryMuscles: ['biceps'],
    secondaryMuscles: ['forearms'],
    instructions: [
      'Stand tall with a dumbbell in each hand.',
      'Curl the weights while keeping your elbows near your sides.',
      'Lower the dumbbells slowly and repeat.',
    ],
    category: 'strength',
  },
  {
    id: 'fallback-arms-2',
    name: 'Bench Dip',
    force: 'push',
    level: 'beginner',
    mechanic: 'compound',
    equipment: 'body only',
    primaryMuscles: ['triceps'],
    secondaryMuscles: ['chest', 'shoulders'],
    instructions: [
      'Place your hands on a bench behind you.',
      'Bend your elbows to lower your body.',
      'Press through your hands to return to the start.',
    ],
    category: 'strength',
  },
  {
    id: 'fallback-chest-1',
    name: 'Push-up',
    force: 'push',
    level: 'beginner',
    mechanic: 'compound',
    equipment: 'body only',
    primaryMuscles: ['chest'],
    secondaryMuscles: ['triceps', 'shoulders'],
    instructions: [
      'Start in a high plank with your hands under your shoulders.',
      'Lower your chest toward the floor.',
      'Push back up while keeping your body in a straight line.',
    ],
    category: 'strength',
  },
  {
    id: 'fallback-chest-2',
    name: 'Dumbbell Bench Press',
    force: 'push',
    level: 'beginner',
    mechanic: 'compound',
    equipment: 'dumbbell',
    primaryMuscles: ['chest'],
    secondaryMuscles: ['triceps', 'shoulders'],
    instructions: [
      'Lie on a bench with a dumbbell in each hand.',
      'Press the weights above your chest.',
      'Lower them until your elbows are slightly below your torso.',
    ],
    category: 'strength',
  },
  {
    id: 'fallback-shoulders-1',
    name: 'Dumbbell Shoulder Press',
    force: 'push',
    level: 'beginner',
    mechanic: 'compound',
    equipment: 'dumbbell',
    primaryMuscles: ['shoulders'],
    secondaryMuscles: ['triceps'],
    instructions: [
      'Hold dumbbells at shoulder height.',
      'Press the weights overhead without leaning back.',
      'Lower with control and repeat.',
    ],
    category: 'strength',
  },
  {
    id: 'fallback-legs-1',
    name: 'Bodyweight Squat',
    force: 'push',
    level: 'beginner',
    mechanic: 'compound',
    equipment: 'body only',
    primaryMuscles: ['quadriceps'],
    secondaryMuscles: ['glutes', 'hamstrings', 'calves'],
    instructions: [
      'Stand with your feet about shoulder-width apart.',
      'Sit your hips back and bend your knees.',
      'Drive through your feet to stand tall again.',
    ],
    category: 'strength',
  },
  {
    id: 'fallback-legs-2',
    name: 'Walking Lunge',
    force: 'push',
    level: 'beginner',
    mechanic: 'compound',
    equipment: 'body only',
    primaryMuscles: ['quadriceps'],
    secondaryMuscles: ['glutes', 'hamstrings', 'calves'],
    instructions: [
      'Step forward and lower until both knees are bent.',
      'Push through the front foot to step into the next rep.',
      'Alternate legs with control.',
    ],
    category: 'strength',
  },
  {
    id: 'fallback-core-1',
    name: 'Plank',
    force: 'static',
    level: 'beginner',
    mechanic: 'isolation',
    equipment: 'body only',
    primaryMuscles: ['abdominals'],
    secondaryMuscles: ['lower back'],
    instructions: [
      'Set your forearms on the floor under your shoulders.',
      'Brace your core and keep your body in a straight line.',
      'Hold without letting your hips sag.',
    ],
    category: 'strength',
  },
  {
    id: 'fallback-cardio-1',
    name: 'Burpee',
    force: null,
    level: 'beginner',
    mechanic: 'compound',
    equipment: 'body only',
    primaryMuscles: [],
    secondaryMuscles: ['quadriceps', 'chest', 'shoulders'],
    instructions: [
      'Squat down and place your hands on the floor.',
      'Jump your feet back into a plank.',
      'Return your feet under you and jump up.',
    ],
    category: 'cardio',
    target: 'cardiovascular system',
  },
  {
    id: 'fallback-neck-1',
    name: 'Neck Flexion Stretch',
    force: 'static',
    level: 'beginner',
    mechanic: 'isolation',
    equipment: 'body only',
    primaryMuscles: ['neck'],
    secondaryMuscles: [],
    instructions: [
      'Sit or stand tall.',
      'Gently lower your chin toward your chest.',
      'Hold briefly, then return to neutral.',
    ],
    category: 'stretching',
  },
];
